# SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2020 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: "QA"

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master ]    

permissions:
    pull-requests: write
    contents: read

concurrency:
    group: qa-build-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    qa:
        runs-on: ubuntu-latest
        steps:
            -   name: Check if secrets are available
                run: echo "ok=${{ secrets.KS_PASS != '' }}" >> "$GITHUB_OUTPUT"
                id: check-secrets
            -   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
            -   name: set up JDK 17
                uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Build QA
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
                env:
                    KS_PASS: ${{ secrets.KS_PASS }}
                    KEY_PASS: ${{ secrets.KEY_PASS }}
                    LOG_USERNAME: ${{ secrets.LOG_USERNAME }}
                    LOG_PASSWORD: ${{ secrets.LOG_PASSWORD }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    sed -i "/qa/,/\}/ s/versionCode .*/versionCode ${{github.event.number}} /" app/build.gradle
                    sed -i "/qa/,/\}/ s/versionName .*/versionName \"${{github.event.number}}\"/" app/build.gradle
                    ./gradlew assembleQaDebug
                    $(find /usr/local/lib/android/sdk/build-tools/*/apksigner | sort | tail -n1) sign  --ks-pass pass:$KS_PASS --key-pass pass:$KEY_PASS --ks-key-alias key0 --ks scripts/QA_keystore.jks app/build/outputs/apk/qa/debug/qa-debug-*.apk
                    scripts/uploadArtifact.sh $LOG_USERNAME $LOG_PASSWORD ${{github.event.number}} ${{github.event.number}}
